name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 158.160.172.203
          username: test-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/django_drf_hw
            git pull origin main
            docker-compose down
            docker-compose up -d --build 